### ISSUE TITLE
Encript-decryp

### ISSUE THREAD

**Issue by marlon122** [bmelad/datapower-jwe-encryption-decryption#1]
Friend, I have a question, if I want to encrypt or decrypt a field but it is in a deeper level, how should I pass the field name parameter? example I want to encrypt the "NameEmployee" field of the following json

{ 
  "Employees":{
        "Info":{
            "NameEmployees":"xxxx"
                }
            }
}

¡¡Thanks for your help!!

**Comment by bmelad** [comment]
I've updated the GatewayScript files, now you might use a backslash for a nested object, for your example you can write Info\NameEmployees and it should work.
Do not forget to update the decryption GatewayScript as well.
