### ISSUE TITLE
Desen

### ISSUE THREAD

**Issue by rpayare** [bmelad/datapower-jwe-encryption-decryption#2]

**Comment by bmelad** [comment]
Hi there,

Can you give an example for the issue you've described?

**Comment by rpayare** [comment]
when we have a Json that start with Cero and the information don't have quotation marks the decryption is not possible
{
   "mensaje":"4589999",
   "document":xxxxxxxxxxxxxxxxxxxxxxx  (Encrypt message = 056)
}

(Fail Decrypt)

**Comment by bmelad** [comment]
OK, now it make sense, your example does not contain a valid JSON, only numeric & boolean values can be without quotation mark, for a valid JSON as an input there shouldn't be any problems.

You can check your JSON structure online using sites like https://jsonlint.com/ etc.

Have a nice day!

**Comment by rpayare** [comment]
Thank you very much and as could add the kid in encrypt
